In [2]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np 

# Iris Dataset

In [3]:
iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [4]:
# view the first 5 rows of the dataframe
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
# adds new column with species names
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [6]:
# create training and test data
df['is_train'] = np.random.uniform(0, 1, len(df)) <= 0.75

df.head() 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa     False  
3  setosa      True  
4  setosa      True

In [7]:
train, test = df[df['is_train']==True], df[df['is_train']==False]

In [8]:
# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 111
Number of observations in the test data: 39


In [9]:
# create list of feature column names
features = df.columns[:4]

features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [10]:
# sinse 'spicies' contains the actual spicies names. We must convert those anmes into digits
y = pd.factorize(train['species'])[0]

y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [11]:
# create an instance of the random forest classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)

clf.fit(train[features], y) 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [12]:
# apply the classifier we trained to test data
clf.predict(test[features]) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
# view predicted probabilities of first 10 observations
clf.predict_proba(test[features])[0:10] 

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.98, 0.02, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

## Evaluate Classifier

In [14]:
# Create actual names for the plants for each predicted plant class
preds = iris.target_names[clf.predict(test[features])]

In [15]:
# view predicted species for first 5 observations
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [16]:
# view actual species for first 5 observations
test['species'].head() 

2     setosa
6     setosa
10    setosa
14    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [17]:
# Confusion Matrix
# Create confusion matrix
pd.crosstab(test['species'], preds, rownames=['Actual Species'], colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0          14          0
virginica               0           0         12

In [18]:
# Feature Importance
list(zip(train[features], clf.feature_importances_)) 

[('sepal length (cm)', 0.10097245101900015),
 ('sepal width (cm)', 0.03166415154752334),
 ('petal length (cm)', 0.4625584392642612),
 ('petal width (cm)', 0.4048049581692152)]

# MTCARS Dataset 

In [19]:
MTCARS_LOCATION = "datasets/mtcars.csv"

In [20]:
mtcars = pd.read_csv(MTCARS_LOCATION) 

In [21]:
# read first 5 rows
mtcars.head()

Unnamed: 0 Unnamed: 1   mpg  cyl   disp  hp  drat     wt   qsec  vs  am  \
0     Datsun        710  22.8    4  108.0  93  3.85  2.320  18.61   1   1   
1       Merc       240D  24.4    4  146.7  62  3.69  3.190  20.00   1   0   
2       Merc        230  22.8    4  140.8  95  3.92  3.150  22.90   1   0   
3       Fiat        128  32.4    4   78.7  66  4.08  2.200  19.47   1   1   
4      Honda      Civic  30.4    4   75.7  52  4.93  1.615  18.52   1   1   

   gear  carb  
0     4     1  
1     4     2  
2     4     2  
3     4     1  
4     4     2

In [22]:
mtcars.tail()

Unnamed: 0 Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
27        AMC    Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
28     Camaro        Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
29    Pontiac   Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
30       Ford    Pantera  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
31   Maserati       Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
27     3     2  
28     3     4  
29     3     2  
30     5     4  
31     5     8

In [52]:
features = np.array(mtcars.columns)
features = np.delete(features, [0,1]) # remove 'Unnamed: 1' and 'Unnamed: 0'


In [53]:
cars = pd.DataFrame(mtcars, columns=features)

In [54]:
cars.head()

mpg  cyl   disp  hp  drat     wt   qsec  vs  am  gear  carb
0  22.8    4  108.0  93  3.85  2.320  18.61   1   1     4     1
1  24.4    4  146.7  62  3.69  3.190  20.00   1   0     4     2
2  22.8    4  140.8  95  3.92  3.150  22.90   1   0     4     2
3  32.4    4   78.7  66  4.08  2.200  19.47   1   1     4     1
4  30.4    4   75.7  52  4.93  1.615  18.52   1   1     4     2

In [56]:
cars['make'] = mtcars['Unnamed: 0']

In [58]:
cars.head()

mpg  cyl   disp  hp  drat     wt   qsec  vs  am  gear  carb    make
0  22.8    4  108.0  93  3.85  2.320  18.61   1   1     4     1  Datsun
1  24.4    4  146.7  62  3.69  3.190  20.00   1   0     4     2    Merc
2  22.8    4  140.8  95  3.92  3.150  22.90   1   0     4     2    Merc
3  32.4    4   78.7  66  4.08  2.200  19.47   1   1     4     1    Fiat
4  30.4    4   75.7  52  4.93  1.615  18.52   1   1     4     2   Honda

In [64]:
cars['is_train'] = np.random.uniform(0, 1, len(cars)) <= 0.65

In [65]:
cars.head()

mpg  cyl   disp  hp  drat     wt   qsec  vs  am  gear  carb    make  \
0  22.8    4  108.0  93  3.85  2.320  18.61   1   1     4     1  Datsun   
1  24.4    4  146.7  62  3.69  3.190  20.00   1   0     4     2    Merc   
2  22.8    4  140.8  95  3.92  3.150  22.90   1   0     4     2    Merc   
3  32.4    4   78.7  66  4.08  2.200  19.47   1   1     4     1    Fiat   
4  30.4    4   75.7  52  4.93  1.615  18.52   1   1     4     2   Honda   

   is_train  
0      True  
1      True  
2     False  
3      True  
4      True

In [66]:
# create test and train set
train, test = cars[cars['is_train']==True], cars[cars['is_train']==False]

In [67]:
# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 23
Number of observations in the test data: 9


In [69]:
y = pd.factorize(train['make'])[0]

In [70]:
y

array([ 0,  1,  2,  3,  4,  2,  5,  6,  7,  8,  9,  1, 10, 11,  1,  1,  1,
       12, 13, 14, 15, 16, 17])

## Train Random Forest Classifier

In [71]:
# Create a random forest Classifier. By convention, clf means 'Classifier'
clf = RandomForestClassifier(n_jobs=2, random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [72]:
# apply test data to classifier
clf.predict(test[features])

array([ 1,  2,  5,  7,  1, 16, 12, 14, 17])

In [73]:
# view predicted probabilities 
clf.predict_proba(test[features]) 

array([[0.13, 0.34, 0.05, 0.  , 0.24, 0.01, 0.09, 0.01, 0.04, 0.07, 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.02],
       [0.03, 0.01, 0.72, 0.07, 0.06, 0.05, 0.04, 0.  , 0.  , 0.02, 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.1 , 0.  , 0.11, 0.14, 0.04, 0.18, 0.18, 0.12, 0.  , 0.  , 0.05,
        0.  , 0.  , 0.  , 0.01, 0.  , 0.01, 0.06],
       [0.03, 0.08, 0.01, 0.  , 0.01, 0.03, 0.14, 0.5 , 0.01, 0.  , 0.1 ,
        0.  , 0.  , 0.02, 0.04, 0.  , 0.02, 0.01],
       [0.02, 0.7 , 0.  , 0.  , 0.01, 0.02, 0.04, 0.05, 0.02, 0.03, 0.02,
        0.  , 0.  , 0.02, 0.03, 0.  , 0.04, 0.  ],
       [0.  , 0.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.01, 0.03,
        0.07, 0.01, 0.03, 0.24, 0.  , 0.45, 0.01],
       [0.  , 0.17, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.07, 0.58, 0.11, 0.  , 0.02, 0.05, 0.  ],
       [0.  , 0.2 , 0.  , 0.  , 0.  , 0.01, 0.  , 0.01, 0.  , 0.11, 0.  ,
        0.04, 0.04, 0.  , 0.39, 0.04, 0.16, 0.  ],


## Evaluate

In [90]:
makes = list(set(cars["make"]))
preds = makes[clf.predict(test[features])]

TypeError: only integer scalar arrays can be converted to a scalar index

In [76]:
preds

1        Merc
2        Merc
5      Toyota
7        Fiat
1        Merc
16       Merc
12      Mazda
14    Valiant
17    Ferrari
Name: make, dtype: object

In [77]:
test['make'].head()

2        Merc
5      Toyota
8     Porsche
12      Mazda
15       Merc
Name: make, dtype: object

In [82]:
# Create confusion matrix
pd.crosstab(test['make'], preds, rownames=['Actual Make'], colnames=['Predicted Make'])

ValueError: cannot reindex from a duplicate axis

## Feature Importance

In [80]:
list(zip(train[features], clf.feature_importances_))

[('mpg', 0.12741755410584288),
 ('cyl', 0.02626044405042036),
 ('disp', 0.1367993093997799),
 ('hp', 0.09758585889111608),
 ('drat', 0.12077689636757255),
 ('wt', 0.1498843329141695),
 ('qsec', 0.15428747663266665),
 ('vs', 0.014277720035760565),
 ('am', 0.03627989971903684),
 ('gear', 0.04076062407400338),
 ('carb', 0.09566988380963141)]